spring:
    application:
        name: realtime-chatapp-persistence-service
    config:
        import: "configserver:"
    cloud:
        config:
            discovery:
                enabled: true
                service-id: realtime-chatapp-config-service

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URI:}
